services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      APPLICATION_ROOT: "/usr/local/tomcat/webapps/ROOT/"
      DATABASE_DRIVER: "org.postgresql.Driver"
      DATABASE_URL: "jdbc:postgresql://localhost:5432/database"
      DATABASE_USER: "user"
      DATABASE_PASS: "password"
      DATABASE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      JWT_SECRET: "ec784fa5-3825-4f41-a147-c3e7ae111d17"
